language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.1.0
  - DJANGO_VERSION=2.0.8
  - DJANGO_VERSION=1.11.15
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -e .[ods,xlsx,xls]
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=simple_import manage.py test
after_success:
  coveralls
sudo: false
